# Use official Node.js LTS image as build stage
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Final stage
FROM node:18-alpine

WORKDIR /app

# Copy only production dependencies and source code
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./

# Expose port
EXPOSE 6000

# Run the application
CMD ["node", "src/app/server.js"]
